//var sandbox = require('nodeunit').utils.sandbox;
//var daylite = sandbox('../js/daylite.js');

var daylite = require('../js/daylite.js');
//define(["js/daylite"], function(daylite) {


/*
AUTOGENERATED by the grunt init task.

  ======== A Handy Little Nodeunit Reference ========
  https://github.com/caolan/nodeunit

  Test methods:
    test.expect(numAssertions)
    test.done()
  Test assertions:
    test.ok(value, [message])
    test.equal(actual, expected, [message])
    test.notEqual(actual, expected, [message])
    test.deepEqual(actual, expected, [message])
    test.notDeepEqual(actual, expected, [message])
    test.strictEqual(actual, expected, [message])
    test.notStrictEqual(actual, expected, [message])
    test.throws(block, [error], [message])
    test.doesNotThrow(block, [error], [message])
    test.ifError(value)
*/

// init: init,
// open: open,
// onDateSelected: onDateSelected

exports['awesome'] = {
  setUp: function(done) {
    // setup here
    done();
  },
  'no args': function(test) {
    test.expect(1);
    // tests here
    //test.equal(daylite.awesome(), 'awesome', 'should be awesome.');
    test.equal(3,3);
    test.done();
  },
  "init with no options": function(test) {
    //test.expect(1);
    daylite.init();
    test.equal(2,2);
    test.done();
  }
};

//});